# Generated by Django 5.0.1 on 2024-01-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dolw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("app", models.CharField(max_length=250, verbose_name="Приложение")),
                ("foto", models.ImageField(upload_to="", verbose_name="Фото")),
                ("ted", models.CharField(max_length=250, verbose_name="Платформы")),
            ],
            options={
                "verbose_name": "Приложение",
                "verbose_name_plural": "Приложения",
            },
        ),
    ]
